spring:
  main:
    banner-mode: "off"
  application:
    name: covid19Tracker

  datasource:
    url: jdbc:mysql://localhost:3306/covid
    #jdbc:mysql://docker-mysql:3306/covid
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        generate_statistics: false

server:
  port: 8080
  servlet:
    context-path: /covid

